### ISSUE TITLE
mac 报错 could not find any library for SDL2 (PYSDL2_DLL_PATH: unset)

### ISSUE THREAD

**Issue by kt123zxc** [wolanx/touch-torch#2]
环境：
机型：mac mini m2
macOS：13.3.1 (a) (22E772610a)

脚本编写完启动报错

报错信息：
Traceback (most recent call last):
  File "/Applications/TouchTorch.app/Contents/Resources/plugins/TouchTorchCore/sdl2/dll.py", line 362, in <module sdl2.dll>
  File "/Applications/TouchTorch.app/Contents/Resources/plugins/TouchTorchCore/sdl2/dll.py", line 253, in __init__
/
RuntimeError: could not find any library for SDL2 (PYSDL2_DLL_PATH: unset)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/TouchTorch.app/Contents/Resources/plugins/TouchTorchCore/__main__.py", line 32, in <module>
  File "/Applications/TouchTorch.app/Contents/Resources/plugins/TouchTorchCore/__main__.py", line 21, in main
  File "/Applications/TouchTorch.app/Contents/Resources/plugins/TouchTorchCore/TouchTorchCore/__init__.py", line 10, in <module TouchTorchCore>
  File "/Applications/TouchTorch.app/Contents/Resources/plugins/TouchTorchCore/TouchTorchCore/core/__init__.py", line 1, in <module TouchTorchCore.core>
  File "/Applications/TouchTorch.app/Contents/Resources/plugins/TouchTorchCore/TouchTorchCore/core/control_helper.py", line 10, in <module TouchTorchCore.core.control_helper>
  File "/Applications/TouchTorch.app/Contents/Resources/plugins/TouchTorchCore/TouchTorchCore/core/thread_sdl.py", line 7, in <module TouchTorchCore.core.thread_sdl>
  File "/Applications/TouchTorch.app/Contents/Resources/plugins/TouchTorchCore/sdl2/__init__.py", line 2, in <module sdl2>
  File "/Applications/TouchTorch.app/Contents/Resources/plugins/TouchTorchCore/sdl2/dll.py", line 364, in <module sdl2.dll>
ImportError: could not find any library for SDL2 (PYSDL2_DLL_PATH: unset)

**Comment by wolanx** [comment]
fix in [24.7.3](https://touch-torch.com/docs/release-note#2473)
区别于系统自带 SDL
